version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: auth_api_springboot
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_api_springboot_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: